export enum MealTypeEnum {
  DANIE_GLOWNE = 'DANIE_GLOWNE',
  ZUPA = 'ZUPA',
  SUROWKA = 'SUROWKA',
  DODATKI = 'DODATKI',
  NAPOJ = 'NAPOJ',
  PIECZYWO = 'PIECZYWO',
  WEDLINA = 'WEDLINA',
  NABIAL = 'NABIAL',
  WARZYWO = 'WARZYWO'
}
